
    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKsg7jp0aj6qipr50856wf6vbw1 
       foreign key (user_id) 
       references users;

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table appUser (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKanjpo5tiapru7an6cw4cu37y4 
       foreign key (user_id) 
       references appUser;

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKanjpo5tiapru7an6cw4cu37y4 
       foreign key (user_id) 
       references users;

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKanjpo5tiapru7an6cw4cu37y4 
       foreign key (user_id) 
       references users;

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKanjpo5tiapru7an6cw4cu37y4 
       foreign key (user_id) 
       references users;

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKanjpo5tiapru7an6cw4cu37y4 
       foreign key (user_id) 
       references users;

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKanjpo5tiapru7an6cw4cu37y4 
       foreign key (user_id) 
       references users;

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKanjpo5tiapru7an6cw4cu37y4 
       foreign key (user_id) 
       references users;

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKanjpo5tiapru7an6cw4cu37y4 
       foreign key (user_id) 
       references users;

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKanjpo5tiapru7an6cw4cu37y4 
       foreign key (user_id) 
       references users;

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKanjpo5tiapru7an6cw4cu37y4 
       foreign key (user_id) 
       references users;

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table "appUser" (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKsg7jp0aj6qipr50856wf6vbw1 
       foreign key (user_id) 
       references "appUser";

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table appUser (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    alter table if exists transaction 
       add constraint FKsg7jp0aj6qipr50856wf6vbw1 
       foreign key (user_id) 
       references appUser;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;

    create table app_user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table transaction (
        amount numeric(38,2),
        category_id bigint,
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        description varchar(255),
        primary key (id)
    );

    alter table if exists transaction 
       add constraint FKegwwjgvn1w2a7ce5b1v63ym4x 
       foreign key (user_id) 
       references app_user;

    alter table if exists transaction 
       add constraint FKgik7ruym8r1n4xngrclc6kiih 
       foreign key (category_id) 
       references category;
