-- ============================================================================
--  FinanceTracker - database schema (PostgreSQL)
--
--  DOCUMENTATION ONLY. This file is NOT on the classpath and is NOT executed
--  by Spring. At runtime the tables are created by Hibernate (spring.jpa.
--  hibernate.ddl-auto). Keep this file in sync by hand, or regenerate it from
--  the entities (see docs note at the bottom).
--
--  Entities: AppUser (app_user), Category (category), Transaction (transaction)
-- ============================================================================

-- ---------------------------------------------------------------------------
--  app_user  <-  com.example.financetracker.domain.AppUser
--  One row per registered user.
-- ---------------------------------------------------------------------------
CREATE TABLE app_user (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL UNIQUE,          -- login username (@Column unique, not null)
    email    VARCHAR(255),                          -- not constrained in the entity yet
    password VARCHAR(255)                           -- BCrypt hash, never the raw password
);

-- ---------------------------------------------------------------------------
--  category  <-  com.example.financetracker.domain.Category
--  Reference/lookup data (Salary, Rent, Supermarket, ...). Currently global,
--  shared by every user.
-- ---------------------------------------------------------------------------
CREATE TABLE category (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(255)   -- enum CategoryType stored as string: INCOME | EXPENSE | TRANSFER
);

-- ---------------------------------------------------------------------------
--  transaction  <-  com.example.financetracker.domain.Transaction
--  One row per money movement, owned by a user and classified by a category.
-- ---------------------------------------------------------------------------
CREATE TABLE transaction (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),                 -- nullable
    date        TIMESTAMP,                    -- set to LocalDateTime.now() on create
    amount      NUMERIC(38, 2),              -- BigDecimal
    category_id BIGINT REFERENCES category (id),          -- nullable (ManyToOne, no nullable=false)
    user_id     BIGINT NOT NULL REFERENCES app_user (id)  -- required owner (ManyToOne, nullable=false)
);

-- ============================================================================
--  RELATIONSHIPS
--
--  app_user (1) ---- (N) transaction      transaction.user_id  -> app_user.id   [required]
--  category (1) ---- (N) transaction      transaction.category_id -> category.id [optional]
--
--  JPA cascade notes (application-level, not DB-level):
--   * AppUser.transactions : cascade=ALL, orphanRemoval=true
--       deleting a user deletes their transactions
--   * Category.transactions: cascade=ALL, orphanRemoval=true
--       deleting a category deletes every transaction in it (be careful)
-- ============================================================================

-- ---------------------------------------------------------------------------
--  Regenerate from the entities instead of editing by hand:
--    spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
--    spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=docs/schema.sql
--  (run once, then remove those properties). Long term: switch to Flyway and
--  let the versioned migrations be the single source of truth.
-- ---------------------------------------------------------------------------
